pipeline {
    agent any

    environment {
        DEV_BRANCH   = 'dev'
        MAIN_BRANCH  = 'main'
        REPO_URL     = 'https://github.com/Rifaq-123/Admin_Module.git'
        DOCKER_IMAGE = 'rifaq123/student-management-backend'
    }

    stages {

        stage('Checkout dev branch') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: "*/${DEV_BRANCH}"]],
                    userRemoteConfigs: [[url: "${REPO_URL}"]]
                ])
            }
        }

        stage('Build Maven Project') {
            steps {
                dir('Backend') {
                    script {
                        if (isUnix()) {
                            sh 'mvn clean package -DskipTests'
                        } else {
                            bat 'mvn clean package -DskipTests'
                        }
                    }
                }
            }
        }

        stage('SonarCloud Analysis') {
            steps {
                dir('Backend') {
                    withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                        script {
                            if (isUnix()) {
                                sh """
                                mvn sonar:sonar \
                                -Dsonar.projectKey=rifaq-123_Admin_Module \
                                -Dsonar.organization=rifaq-123 \
                                -Dsonar.host.url=https://sonarcloud.io \
                                -Dsonar.token=\$SONAR_TOKEN \
                                -Dsonar.branch.name=dev
                                """
                            } else {
                                bat """
                                mvn sonar:sonar ^
                                -Dsonar.projectKey=rifaq-123_Admin_Module ^
                                -Dsonar.organization=rifaq-123 ^
                                -Dsonar.host.url=https://sonarcloud.io ^
                                -Dsonar.token=%SONAR_TOKEN% ^
                                -Dsonar.branch.name=dev
                                """
                            }
                        }
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Backend') {
                    script {
                        if (isUnix()) {
                            sh 'docker build -t student-management-backend .'
                        } else {
                            bat 'docker build -t student-management-backend .'
                        }
                    }
                }
            }
        }

        stage('Tag Docker Image') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'docker tag student-management-backend $DOCKER_IMAGE:latest'
                    } else {
                        bat 'docker tag student-management-backend %DOCKER_IMAGE%:latest'
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    script {

                        if (isUnix()) {

                            sh '''
                            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                            docker push $DOCKER_IMAGE:latest
                            docker logout
                            '''

                        } else {

                            powershell '''
                            docker logout 2>$null

                            docker login `
                              --username "$env:DOCKER_USER" `
                              --password "$env:DOCKER_PASS"

                            docker push "$env:DOCKER_IMAGE`:latest"

                            docker logout
                            '''
                        }
                    }
                }
            }
        }

        stage('Promote dev to main') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'github-credentials',
                    usernameVariable: 'GIT_USER',
                    passwordVariable: 'GIT_PASS'
                )]) {
                    script {
                        if (isUnix()) {
                            sh '''
                            git config user.name "$GIT_USER"
                            git config user.email "jenkins@example.com"

                            git fetch origin
                            git checkout main || git checkout -b main
                            git pull origin main --rebase
                            git merge origin/dev --no-edit
                            git push https://$GIT_USER:$GIT_PASS@github.com/Rifaq-123/Admin_Module.git main
                            '''
                        } else {
                            bat '''
                            git config user.name "%GIT_USER%"
                            git config user.email "jenkins@example.com"

                            git fetch origin
                            git checkout main || git checkout -b main
                            git pull origin main --rebase
                            git merge origin/dev --no-edit
                            git push https://%GIT_USER%:%GIT_PASS%@github.com/Rifaq-123/Admin_Module.git main
                            '''
                        }
                    }
                }
            }
        }

    }

    post {
        success {
            echo 'SUCCESS: Pipeline completed.'
        }
        failure {
            echo 'FAILED: Fix errors.'
        }
    }
}